#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/pip"
else
    PIP="$PYTHON -m pip"
fi

${PIP} install -U pip
PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 ${PIP} install -r "$REQUIREMENTS"
