#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/python -m pip"
else
    PIP="$PYTHON -m pip"
fi

"$PIP" install -r "requirements-pypa.txt"
"$PIP" install -r "$REQUIREMENTS"
