#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
    export PATH=${PREFIX}:${PATH}
fi
export SOURCE_FILES="uvicorn tests"

set -x

${PREFIX}black --target-version=py37 $SOURCE_FILES
${PREFIX}ruff --fix $SOURCE_FILES
${PREFIX}python -m tools.cli_usage
