#!/bin/sh

export PREFIX=""
if [ -d 'venv' ]; then
    export PREFIX="venv/bin/"
fi

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi

export COVERAGE_PROCESS_START=$(pwd)/pyproject.toml

${PREFIX}coverage run --debug config -m pytest "$@"

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
