#!/bin/sh

export PREFIX=""
if [ -d 'venv' ]; then
    export PREFIX="venv/bin/"
fi

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi

${PREFIX}coverage run --debug config -m pytest
#PYTHONWARNINGS=all PYTHONTRACEMALLOC=25 ${PREFIX}coverage run --debug config -m pytest
#PYTHONWARNINGS=all PYTHONTRACEMALLOC=25 pytest -W error -p no:warnings -s tests

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
